apiVersion: apps/v1
kind: Deployment
metadata:
  name: date-time-webapp
  labels:
    app: date-time
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: date-time
  template:
    metadata:
      labels:
        app: date-time
        env: prod
    spec:  
      containers:
        - name: date-time-container
          image: 141409473062.dkr.ecr.us-east-1.amazonaws.com/date-time-webapp:v2
          ports:
          - containerPort: 8080
    
    
