apiVersion: v1
kind: Service
metadata:
  name: date-time-service
spec:
  type: NodePort
  selector:
    app: date-time
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      NodePort: 31122
